-- Command line was: E:\github\dhgametool\scripts\config\strings\ms\arena.lua 

local arena = {}
arena[1] = {name = "Liga Mahkota Kristal", des = "Permainan kitaran memberikan ganjaran harian yang hebat dan ganjaran bermusim", infoTitle1 = "Peraturan Pertempuran", info1 = "1. Ganjaran kedudukan dihantar kepada pemenang pada jam 21:00 (UTC/GMT 0) setiap hari; 2. Setiap pertempuran arena akan dikenakan bayaran tiket arena yang boleh dibeli dengan berlian; 3. Setiap pertempuran arena berlangsung selama 15 pusingan. Jika pertempuran melebihi had masa yang ditetapkan, penyerang akan kalah; 4. Setiap pertempuran memberikan mata tertentu yang menetapkan kedudukan; 5. Anda boleh menonton tayangan semula 10 pertempuran terbaru dalam Log Pertempuran", infoTitle2 = "Peraturan Ganjaran", info2 = "Ganjaran akan dihantar kepada pemain kedudukan paling tinggi setiap hari; Untuk mendapatkan butiran, sila semak Ganjaran", date = "8 Jun - 8 Julai"}
arena[3] = {name = "Piala Dunia Pedalaman", des = "Perlukan: Kuasa\226\137\165150,000", infoTitle1 = "Peraturan Pertempuran", info1 = "1. Setiap pertempuran arena berlangsung selama 15 pusingan. Apabila pertempuran melebihi had masa yang ditetapkan, penyerang akan kalah; 2. Setiap pertempuran memberikan mata tertentu yang menetapkan kedudukan; 3. Anda boleh menonton tayangan semula 10 pertempuran terbaru dalam Log Pertempuran", infoTitle2 = "Peraturan Ganjaran", info2 = "Apabila acara tamat, ganjaran akan ditawarkan berdasarkan pada kedudukan", date = "8 Jun - 8 Julai"}
arena[2] = {name = "Percubaan Juara", des = "Keperluan: Tahap Pemain 55.", infoTitle1 = "Peraturan Pertempuran", info1 = "1. Pemain boleh mengubah suai 3 pasukan pertahanan mereka pada bila-bila masa. Setiap formasi perlu mengandungi sekurang-kurangnya 1 wira; 2. Pertempuran menggunakan mod tiga terbaik. Sesiapa yang memenangi 2 permainan akan menang; 3. Menewaskan semua wira dalam satu pasukan akan dikira menang 1 pertempuran; 4.  Setiap pertempuran arena berlangsung selama 15 pusingan. Apabila pertempuran melebihi had masa yang ditetapkan, penyerang akan kalah; 5. Setiap pertempuran memberikan mata tertentu yang menetapkan kedudukan; 6. Anda boleh menonton tayangan semula 10 pertempuran terbaru dalam Log Pertempuran", infoTitle2 = "Peraturan Ganjaran", info2 = "Apabila acara tamat, ganjaran akan ditawarkan berdasarkan pada kedudukan. Item dalam Peti Arena yang anda menangi berdasarkan kedudukan anda akan dihantar melalui mel dalam permainan apabila pertandingan berakhir. ", date = "8 Jun - 8 Julai"}
arena[4] = {name = "Arena Berpasukan Bebas", des = "Keperluan: Tahap Pemain 60.", infoTitle1 = "Peraturan Pertempuran", info1 = "1. Arena Berpasukan Bebas dibuka dari 0:00 AM (UTC/GMT 0) Selasa hingga 23:59 PM (UTC/GMT 0) Khamis. ;2. Selepas memasuki Arena Berpasukan Bebas, pemain boleh memilih satu pasukan untuk disertai atau membina pasukan anda sendiri untuk menjemput pemain lain. ;3. Pemain daripada pelayan lain tidak boleh menjadi ahli pasukan. ;4. Hanya pemilik pasukan boleh mengatur susunan perlawanan dan memilih pasukan lawan, manakala ahli lain hanya boleh menyemak rekod pertempuran. ;5. Setiap pasukan mempunyai 6 tenaga pada waktu permulaan selepas pasukan Dibina dan tenaga akan pulih 1 mata setiap jam dan boleh disimpan sehingga 12 mata. Setiap pertempuran akan menggunakan 1 tenaga. ;6. Sekurang-kurangnya 1 wira hendaklah dipilih dalam barisan ahli pasukan anda dan pemain boleh mengubah suainya pada bila-bila masa. ;7. Setiap pertempuran terdiri daripada 3 Perlawanan. Pasukan yang terlebih dahulu memenangi dua Perlawanan akan mendapat kemenangan. ;8. Tewaskan semua wira pasukan lawan untuk memenangi Perlawanan. ;9. Setiap Perlawanan berlangsung selama 15 pusingan, tamat masa akan menyebabkan pasukan penyerang kalah. ;10. Selepas setiap pertempuran, pasukan yang menang mendapat mata arena dan pasukan yang tewas akan kehilangan mata arena, semua pasukan akan diberi kedudukan mengikut jumlah mata arena mereka. ;11. Pemain boleh menonton klip video bagi 10 pertempuran terakhir mereka dalam Rakaman Pertempuran.", infoTitle2 = "Peraturan Ganjaran", info2 = "Apabila acara tamat, ganjaran akan ditawarkan berdasarkan pada kedudukan", date = "8 Jun - 8 Julai"}
return arena

