-- Command line was: E:\github\dhgametool\scripts\config\strings\it\arena.lua 

local arena = {}
arena[1] = {name = "Lega della corona di cristallo", des = "Il gioco ciclico fa guadagnare ricche ricompense giornaliere e stagionali", infoTitle1 = "Regole della battaglia", info1 = "1. Le ricompense classifica sono inviate ai vincitori quotidianamente alle ore 21.00 (UTC/GMT 0); 2. Ogni battaglia nell'arena ha un costo di un biglietto arena. I biglietti arena si possono acquistare con i diamanti; 3. Ogni battaglia nell'arena ha una durata di 15 round. Se la battaglia si protrae oltre il limite di tempo, la squadra attaccante perde; 4. Ogni battaglia fa guadagnare dei punti, che determinano la posizione in classifica; 5. Le ultime 10 battaglie si possono rivedere accedendo all'apposito registro", infoTitle2 = "Regole relative alle ricompense", info2 = "Le ricompense saranno inviate quotidianamente ai primi giocatori classificati; per i dettagli, consultare Ricompensa", date = "June 8th - July 8th"}
arena[3] = {name = "Coppa del mondo del regno", des = "Caratteristiche necessarie: Potenza\226\137\165150.000", infoTitle1 = "Regole della battaglia", info1 = "1. Ogni battaglia nell'arena ha una durata di 15 round. Se la battaglia si protrae oltre il limite di tempo, la squadra attaccante perde; 2. Ogni battaglia fa guadagnare dei punti, che determinano la posizione in classifica; 3. Le ultime 10 battaglie si possono rivedere accedendo all'apposito registro", infoTitle2 = "Regole relative alle ricompense", info2 = "Al termine dell'evento, si riceveranno delle ricompense in base alla posizione in classifica", date = "June 8th - July 8th"}
arena[2] = {name = "Prova del campione", des = "Requisiti: Livello giocatore 55.", infoTitle1 = "Regole della battaglia", info1 = "1. I giocatori possono modificare le 3 squadre di difesa ogni volta che lo desiderano. Ogni formazione deve comprendere almeno 1 eroe; 2. La modalit\195\160 di battaglia privilegia il migliore dei tre. La vittoria spetta a chi vince 2 incontri; 3. Per vincere 1 battaglia, si devono sconfiggere tutti gli eroi di una squadra; 4.  Ogni battaglia nell'arena ha una durata di 15 round. Se la battaglia si protrae oltre il limite di tempo, la squadra attaccante perde; 5. Ogni battaglia fa guadagnare dei punti, che determinano la posizione in classifica; 6. Le ultime 10 battaglie si possono rivedere accedendo all'apposito registro", infoTitle2 = "Regole relative alle ricompense", info2 = "Al termine dell'evento, si riceveranno delle ricompense in base alla posizione in classifica. Gli oggetti del forziere dell'arena, vinti in base alla posizione in classifica, saranno inviati tramite messaggio del gioco al termine del torneo. ", date = "June 8th - July 8th"}
arena[4] = {name = "Arena a squadre libere", des = "Requisiti: Livello giocatore 60.", infoTitle1 = "Regole della battaglia", info1 = "1. L'arena a squadre libere \195\168 aperta dalle ore 0.00 (UTC/GMT 0) del marted\195\172 alle ore 23.59 (UTC/GMT 0) del gioved\195\172. ;2. Dopo l'accesso all'arena a squadre libere, i giocatori possono unirsi a una squadra esistente o crearne una nuova e invitare gli altri giocatori a partecipare. ;3. I giocatori attivi su diversi server non possono fare squadra tra loro. ;4. Solo il proprietario della squadra pu\195\178 stabilire l'ordine di combattimento e scegliere la squadra rivale, mentre gli altri membri possono soltanto rivedere i record di battaglia. ;5. All'inizio, dopo la creazione, tutte le squadre hanno 6 punti energia; ogni ora si recupera 1 punto energia fino a un massimo di 12 punti energia totali.  Ogni battaglia consuma 1 punto energia. ;6. Nella formazione della squadra deve essere selezionato almeno 1 eroe e i giocatori possono modificarlo in qualsiasi momento. ;7. Ogni battaglia comprende 3 incontri. La squadra che vince due incontri per prima conquista la vittoria finale. ;8. Per vincere l'incontro, si devono sconfiggere tutti gli eroi della squadra avversaria. ;9. Ogni incontro ha una durata di 15 round; allo scadere del tempo, la squadra attaccante perde l'incontro. ;10. Dopo ogni battaglia, la squadra vincitrice guadagna punti arena, mentre quelle sconfitte perdono punti arena; tutte le squadre conquistano una posizione in classifica in base ai punti arena totali. ;11. I giocatori possono guardare i video delle ultime 10 battaglie accedendo agli appositi registri.", infoTitle2 = "Regole relative alle ricompense", info2 = "Al termine dell'evento, si riceveranno delle ricompense in base alla posizione in classifica", date = "June 8th - July 8th"}
return arena

