-- Command line was: E:\github\dhgametool\scripts\config\strings\de\arena.lua 

local arena = {}
arena[1] = {name = "Crystal Crown League", des = "W\195\182chentliches Rundentu nier; gewinnen Sie viele Tages- und Saisonbelohnungen", infoTitle1 = "Schlachtregeln", info1 = "1. T\195\164glich um 21 Uhr (UTC/GMT 0) werden Rangbelohnungen in Nachrichten verteilt; 2. Eine Teilnahme an Arenaschlachten kostet Tickets, die Sie mit Diamanten kaufen k\195\182nnen; 3. Arenaschlachten sind auf 15 Runden begrenzt. \195\156berschreitet die Schlacht die vorgegebene Zeit, hat der Angreifer verloren; 4. Nach der Schlacht werden die Punkte berechnet, die als Referenzpunkt f\195\188r Ihren Spielerrang dienen; 5. Im Schlachtverlauf k\195\182nnen Sie sich die Videos von den letzten 10 Schlachten ansehen", infoTitle2 = "Belohnungsregeln", info2 = "Das Ausmailen von Preisen f\195\188r das t\195\164gliche Ranking basiert auf dem Rang zur Rangzeit. F\195\188r Bestimmtes bitte schau unter t\195\164gliche Belohnungen.", date = "8.6. bis zum 8.7."}
arena[3] = {name = "K\195\182nigsruf", des = "Anforderung: Kampfkraft\226\137\165150.000", infoTitle1 = "Schlachtregeln", info1 = "1. Arenaschlachten sind auf 15 Runden begrenzt. \195\156berschreitet die Schlacht die vorgegebene Zeit, hat der Angreifer verloren; 2. Nach der Schlacht werden die Punkte berechnet, die als Referenzpunkt f\195\188r Ihren Spielerrang dienen; 3. Im Schlachtverlauf k\195\182nnen Sie sich die Videos von den letzten 10 Schlachten ansehen", infoTitle2 = "Belohnungsregeln", info2 = "Nach der Veranstaltung wird die Belohnung gem\195\164\195\159 dem Rang ausgegeben.", date = "8.6. bis zum 8.7."}
arena[2] = {name = "Championtraining", des = "Anforderung: Spieler-Lv 55", infoTitle1 = "Schlachtregeln", info1 = "1. Spieler k\195\182nnen mit der Zeit ihre Verteidigungsaufstellung korrigieren. Sie m\195\188ssen 3 Heldentruppen einsetzen, in jeder Truppe muss sich min. 1 Mensch befinden; 2. Sie m\195\188ssen zwei Siege in 3 K\195\164mpfen erzielen, um die Schlacht zu gewinnen; 3. Wenn Sie alle Helden Ihres Gegners besiegen, gilt die Schlacht als gewonnen; 4. Arenaschlachten sind auf 15 Runden begrenzt. \195\156berschreitet die Schlacht die vorgegebene Zeit, hat der Angreifer verloren; 5. Nach der Schlacht werden die Punkte berechnet, die als Referenzpunkt f\195\188r Ihren Spielerrang dienen; 6. Im Schlachtverlauf k\195\182nnen Sie sich die Videos von den letzten 10 Schlachten ansehen", infoTitle2 = "Belohnungsregeln", info2 = "Nach der Veranstaltung wird die Belohnung gem\195\164\195\159 dem Rang ausgegeben.", date = "8.6. bis zum 8.7."}
arena[4] = {name = "Free team up arena", des = "Anforderung: Spieler-Lv 60", infoTitle1 = "Schlachtregeln", info1 = "1.\195\150ffnungszeiten der Reihe-Arena : w\195\182chentlich von Dienstag 0:00 bis Donnerstag 23:59 (UTC/GMT) \195\182ffnen. ;2.Nach der Eintretung der Reihe kann Spieler nicht nur eine Reihe w\195\164hlen, sondern auch eine Reihe organisieren und andere Spieler einladen, Arena zu teilnehmen ;3.Nur aus gliechen Servern k\195\182nnen Spieler Reihe organisieren, Spieler aus verschiedenen Servern k\195\182nnen nicht Reihe oganisieren. ;4.Jede Reihe muss durch Leader Schlachtsreihenfolge geordnet werden und die Reihe gew\195\164hlt werden, herauszufordern. Andere Mannschaftsmitglieder k\195\182nnen nur Schlachtsprotokoll nachsehen. ;5. Nach der Schaffung der Reihe gibt es 6 Energien, jede Reihe erh\195\164ltet 1 Energie pro Stunde und besitzt maximal 12 Energien. Jede Herausforderung verbraucht 1 Energie. Wenn die Energie 0 ist, kann die Herausforderung nicht stattfinden. ;6.In der Aufstellung der Reihe-Arena muss es mindestens 1 Held geben, Spieler kann jederzeit Aufstellung regeln. ;7.Die Schlachtssystem verlangt zwei Siege in drei Spiele, die Reihe mit 2 Siege gewinnt. ;8.Die Reihe gewinnt, wenn er \195\188ber alle Helden von Gegner triumphiert. ;9.Die Schlacht muss in 15 Runde enden, sonst scheitert die Offensive. ;10. Nach der Schlacht gibt es Integrationsrechnung als Grundlage f\195\188r die Reihe-Rang. ;11. In dem Schlachtsprotokoll kann Spieler letzten 10 Schlachtensvideoaufnahme nachsehen.", infoTitle2 = "Belohnungsregeln", info2 = "Nach der Veranstaltung wird die Belohnung gem\195\164\195\159 dem Rang ausgegeben.", date = "8.6. bis zum 8.7."}
return arena

