-- Command line was: E:\github\dhgametool\scripts\config\strings\us\arena.lua 

local arena = {}
arena[1] = {name = "Crystal Crown League", des = "The cycle game grants great daily rewards and seasonal rewards", infoTitle1 = "Battle Rules", info1 = "1. The ranking rewards are sent to winners at 21:00 (UTC/GMT 0)daily; 2. Each arena battle costs arena ticket that you can buy with diamonds; 3. Each arena battle lasts 15 rounds. If battle exceeds the time limit,  the attacker will lose; 4. Each battle grants certain points that set the ranking; 5. You check out the most recent 10 battles replays in Battle Log", infoTitle2 = "Reward Rules", info2 = "Rewards will be sent to the highest ranking players every day; For details,  please check Reward", date = "June 8th - July 8th"}
arena[3] = {name = "Inland World Cup", des = "Require: Power\226\137\165150,000", infoTitle1 = "Battle Rules", info1 = "1. Each arena battle lasts for 15 rounds. When battle exceeds the time limit,  the attacker will lose; 2. Each battle grants certain points that set the ranking; 3. You could check out the most recent 10 battles replays in Battle Log", infoTitle2 = "Reward Rules", info2 = "When the event is over,  rewards will be offered based on the rankings", date = "June 8th - July 8th"}
arena[2] = {name = "Trial Of The Champion", des = "Requirement: Player Level 55.", infoTitle1 = "Battle Rules", info1 = "1. Players could adjust their 3 defense teams whenever they want. Each formation needs to contain at least 1 hero; 2. The battle takes best-of-three mode. The part who wins 2 games will win; 3. Defeating all heroes of a team wins 1 battle; 4.  Each arena battle lasts for 15 rounds. When battle exceeds the time limit,  the attacker will lose; 5. Each battle grants certain points that set the ranking; 6. You could check out the most recent 10 battles replays in Battle Log", infoTitle2 = "Reward Rules", info2 = "When the event is over,  rewards will be offered based on the rankings. Items in Arena Chest you won basing on your ranking, will be sent by in game mail when the tournament is over. ", date = "June 8th - July 8th"}
arena[4] = {name = "Free Team-up Arena", des = "Requirement: Player Level 60.", infoTitle1 = "Battle Rules", info1 = "1. Free Team-up Arena opens from 0:00 AM (UTC/GMT 0) Tuesday to 23:59 PM (UTC/GMT 0) Thursday. ;2. After entering Free Team-up Arena, players can choose one team to join or create your own team to invite other players. ;3. Players from different servers are not able to team up. ;4. Only team owner can arrange fight order and choose the rival team, while other members can only check the battle records. ;5. Each team has 6 energy at the very beginning after team Created and energy recovers 1 point each hour and can be stored up to 12 points. Each battle consumes 1 energy. ;6. At least 1 hero should be selected in your team lineup and players can adjust it any time. ;7. Each battle consists of 3 Fights. Team that wins two Fights first will gain the final victory. ;8. Defeat all heroes of opposite team to win the Fight. ;9. Each Fight lasts 15 rounds, timeout will cause attacking team losing the fight. ;10. After each battle, victory team gains arena points, and defeat teams lose arena points, all the teams will be ranked by their total arena points. ;11. Players can watch their last 10 battle video clips in Battle Records.", infoTitle2 = "Reward Rules", info2 = "When the event is over,  rewards will be offered based on the rankings", date = "June 8th - July 8th"}
return arena

