-- Command line was: E:\github\dhgametool\scripts\config\strings\us\faq.lua 

local faq = {}
faq[1] = {title = "General Questions", describe = "1.Q:I have just changed my device. How do I continue the game?|A:1. Download the game on the new device. 2.Tap the human icon on the top right corner. 3. Enter your account and password.|2.Q:I have forgotten my account. How do I recover it?|A:It is impossible to recover the forgotten account. So please remember your account and password.|3.Q:My account has been stolen and password changed. What do I do?|A:If your password has been changed, contact our customer service immediately.|4.Q:I can't login after the network has timed out. What do I do?|A:1. Try to reconnect. 2. Force close the game and restart it.|5.Q:The game keeps checking for updates and I can't enter the game. What do I do?|A:1.  Force close the game and restart it. 2. If 1 doesn't work, connect to another network and try again. 3. If 1 and 2 does not resolve your issue, contact our customer service.|6.Q:What should I do when my data or account is lost?|A:1. Make sure you are on the correct server. Data is not shared among different servers. 2. If the server is correct, please provide your ID and registered email to our customer service. We will help you ASAP.|7.Q:I keep going offline. What do I do?|A:1. Check your network connection. 2. Try new connections. 3. If 1 and 2 do not work, please contact our customer service.|8.Q:The game crashed. What do I do?|A:1. Force close the game and restart it. 2. Try method 1 several times. 3. If 1 and 2 does not work, please provide your device type to the customer service and we will help you ASAP.|9.Q:I have found some cheaters. What do I do?|A:Fair environment and good balance are what we care about most. When you find cheaters in the game, report them to us and we will handle them ASAP."}
faq[2] = {title = "General Social Questions", describe = "1.Q:Some players are spamming the chat. What do I do?|A:1. Right click a player's avatar in chat. 2. Click Block to block the player.|2.Q:Some players are posting ads or fraudulent information in chat. What do I do?|A:1. Tap Feedback on the left of the main page. 2. Report the player ID to our customer service. 3. You can also report a player by providing a screen shot and player ID through email.|3.Q:How do I add friends in the game?|A:1. Tap the player's avatar in chat to send request. 2. Enter the player ID in the friend page. 3. Send requests to recommended players.|4.Q:How do I interact with friends?|A:1. Friends can help each other in defeating bosses. 2. Friends can send hearts to each other. Hearts can be used in Heart Summons. 3. You can communicate with friends though Mail.|5.Q:How do I join a Guild?|A:1. Tap the Guild icon on the main page. 2. Choose a recommended Guild or search for one with the Guild ID. 3. Create your own Guild and invite other players.|6.Q:What can I do when in a Guild?|A:1. Check in daily to level up the Guild and win Guild coins. 2. Get Guild coins and gold from the Windmill and Raid. 3. Sign up for the weekly Guild War for a chance to earn Guild coins and other rewards.|7.Q:What will happen when I change Guilds?|A:If you have applied to join the guild war, you can't join the Guild War of the week or get any guild war rewards if you change guilds.|8.Q:What are guild coins for?|A:Guild coins can be used to buy items in the Guild store and upgrade Guild skills through Guild Tech.|9.Q:What can I gain from upgrading Guild Techs?|A:Upgrading skills of 5 classes in Guild Tech increases corresponding hero stats."}
faq[3] = {title = "General Payment Questions", describe = "1.Q:How do I become a VIP Player?|A:You can become a VIP after buying the required number of diamonds. The more diamonds bought, the higher the VIP level and more privileges.|2.Q:What can I get from the 1st Top-up?|A:The 1st top-up grants double diamonds. Each level is available once only. Special offers (like the monthly card) are not included.|3.Q:I have paid for items but did not receive them while charging, what do I do?|A:1. Restart the game and check your account. 2. Repeat 1.  3. Contact our customer service in time.|4.Q:What I paid is not the same as what I am charged. Why?|A:The payment changes according to the variation in the exchange rate."}
faq[4] = {title = "Contact Us", describe = "If you have any problems or suggestions, please contact us through Support or by mail. Our email address is: ihcs@droidhang.com"}
return faq

