-- Command line was: scripts\config.lua 

DEBUG = 0
DEBUG_FPS = false
DEBUG_MEM = false
CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN = 2
CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN = 4
CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN_RECV = 2
CONFIG_PROTOCOL_HEADER_LEN = CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN + CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN
CONFIG_PROTOCOL_HEADER_LEN_RECV = CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN + CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN_RECV

