-- Command line was: E:\github\dhgametool\scripts\config\strings\es\arena.lua 

local arena = {}
arena[1] = {name = "Liga De La Corona De Cristal", des = "El juego del ciclo otorga grandes recompensas diarias y recompensas de temporada", infoTitle1 = "Reglas de la Batalla", info1 = "1. Las recompensas por rango son enviadas diariamente a los ganadores a las 21:00 (UTC/GMT 0); 2. Cada batalla en la arena cuesta boletos de la arena que se pueden comprar con diamantes; 3. Cada batalla en la arena dura 15 rondas de batalla. Si la batalla excede el l\195\173mite de tiempo, el atacante perder\195\161; 4. Cada batalla otorga ciertos puntos que marcan el rango; 5. Usted revise las 10 batallas m\195\161s recientes en las repeticiones en Batalla Log", infoTitle2 = "Reglas de las Recompensas", info2 = "Las recompensas ser\195\161n enviadas a los jugadores con el mayor  rango todos los d\195\173as; Para los detalles, por favor, compruebe la Recompensa", date = "Junio 8 - Julio 8"}
arena[3] = {name = "Copa Mundial Interna", des = "Requiere: Poder\226\137\165150,000", infoTitle1 = "Reglas de la Batalla", info1 = "1. Cada batalla en la arena tiene una duraci\195\179n de 15 rondas. Cuando la batalla excede el l\195\173mite de tiempo, el atacante perder\195\161; 2. Cada batalla otorga ciertos puntos que marcan el rango; 3. Usted puede revisar los 10 batallas m\195\161s 10 recientes en las repeticiones en Batalla Log", infoTitle2 = "Reglas de las Recompensas", info2 = "Cuando termine el evento, los premios ser\195\161n ofrecidos conforme a los rangos", date = "Junio 8 - Julio 8"}
arena[2] = {name = "Prueba Del Campeon", des = "Requisito: Nivel 55 del Jugador.", infoTitle1 = "Reglas de la Batalla", info1 = "1. Los jugadores pueden ajustar sus 3 equipos de defensa cuando quieran. Cada formaci\195\179n tiene que contener al menos 1 h\195\169roe; 2. La batalla tiene al mejor de los tres modos. La parte que gana 2 juegos ganar\195\161; 3. Al derrotar a todos los h\195\169roes de un equipo gana 1 batalla; 4. Cada batalla en la arena tiene una duraci\195\179n de 15 rondas de batalla. Cuando la batalla excede el l\195\173mite de tiempo, el atacante perder\195\161; 5. Cada batalla otorga ciertos puntos que marcan el rango; 6. Usted revise las 10 batallas m\195\161s recientes en las repeticiones en Batalla Log", infoTitle2 = "Reglas de las Recompensas", info2 = "Cuando termine el evento, los premios ser\195\161n ofrecidos conforme a los rangos. Los art\195\173culos que usted gan\195\179 en el Tesoro de la Arena  basados en su clasificaci\195\179n, ser\195\161n enviados por el correo del juego cuando termine el torneo.", date = "Junio 8 - Julio 8"}
arena[4] = {name = "Equipo Libre de la Arena", des = "Requisito: Nivel 60 del Jugador.", infoTitle1 = "Reglas de la Batalla", info1 = "1. El Equipo Libre de la Arena comienza a las 0:00 AM (UTC/GMT 0) Martes a las 23:59 PM (UTC/GMT 0) Jueves.;2. Despues de ingresar al Equipo Libre de la Arena, los jugadores pueden elegir unirse a un equipo o invitar a otros jugadores.;3. Los jugadores de diferentes servidores no pueden formar equipo.; 4. S\195\179lo el propietario del equipo puede organizar el orden de la pelea y elegir el equipo rival, mientras que otros miembros s\195\179lo pueden revisar el registro de la batalla.; 5. Al inicio cada equipo Creado tiene 6 de energ\195\173a y la energ\195\173a recupera 1 punto cada hora y puede almacenarse hasta 12 puntos. Cada batalla consume 1 de energ\195\173a.; 6. Al menos un h\195\169roe debe ser seleccionado en la alineaci\195\179n de su equipo y los jugadores pueden ajustarse en cualquier momento.; 7. Cada batalla consiste en 3 peleas. El primer equipo que gana dos peleas ganar\195\161 la victoria final.; 8. Derrotar a todos los h\195\169roes del equipo contrario para ganar la pelea.; 9.  Cada Batalla dura 15 rondas, el tiempo de espera causara que el equipo atacado pierda la pelea.; 10. Despu\195\169s de cada batalla, el equipo victorioso gana puntos de la arena, y los equipos derrotados pierden puntos de arena, todos los equipos ser\195\161n clasificados por su total de puntos de la arena.; 11. Los jugadores pueden ver sus \195\186ltimos 10 videoclips de batalla en los Registros de la Batalla.", infoTitle2 = "Reglas de las Recompensas", info2 = "Cuando termine el evento, los premios ser\195\161n ofrecidos conforme a los rangos", date = "June 8th - July 8th"}
return arena

